# Workflow name
name: "Vporfile IAC"

# Trigger the workflow on push or pull request to specific branches and paths
on:
  push:
    branches:
      - main       # Run on push to 'main'
      - stage      # Run on push to 'stage'
    paths:
      - terraform/**  # Only if files in 'terraform/' are changed
  pull_request:
    branches:
      - main       # Run on PR to 'main'
    paths:
      - terraform/**  # Only if files in 'terraform/' are affected

# Set environment variables available to all jobs
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}             # AWS access key from secrets
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     # AWS secret key from secrets
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}                 # Terraform backend bucket name from secrets
  AWS_REGION: us-east-2                                           # AWS region
  EKS_CLUSTER: vprofile-eks                                       # EKS cluster name

jobs:
  terraform:
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest                                        # Use latest Ubuntu runner

    defaults:
      run:
        shell: bash                                               # Use Bash shell
        working-directory: ./terraform                            # Set working directory for all run steps

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4                                 # Checks out the repo content to the runner

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2                        # Installs Terraform CLI
        # Optional version specification commented out
        # with:
        #   terraform_version: 1.6.3

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"  # Initializes Terraform with backend config

      - name: Terraform format
        id: fmt
        run: terraform fmt -check                                # Checks formatting of Terraform files

      - name: Terraform validate
        id: validate
        run: terraform validate                                   # Validates Terraform configuration

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile # Creates an execution plan
        continue-on-error: true                                  # Allows workflow to continue even if plan fails

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'                      # Only run if the plan step failed
        run: exit 1                                              # Forces a failure in the workflow




        
        
        
        
        
        
        
/*

Workflow Triggers
Push Events: Runs when changes are pushed to main or stage branches, specifically targeting Terraform files (terraform/**).

Pull Requests: Executes for pull requests to main, ensuring Terraform modifications are validated before merging.

Environment Variables
AWS Credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY): Stored securely in GitHub secrets for authentication.

Terraform State Storage (BUCKET_TF_STATE): Specifies the S3 bucket used to persist Terraform state.

AWS Configuration (AWS_REGION): Defines the deployment region as us-east-2.

EKS Cluster Reference (EKS_CLUSTER): Sets the target Kubernetes cluster for Terraform provisioning.

Job Execution (terraform)
Runs on ubuntu-latest: Uses a Linux runner for Terraform execution.

Sets Default Shell & Working Directory: Ensures Terraform commands execute correctly within ./terraform.

Steps Breakdown
Checkout Repository: Pulls the source code (actions/checkout@v4).

Setup Terraform: Installs Terraform on the runner (hashicorp/setup-terraform@v2).

Initialize Terraform (terraform init): Configures backend storage using the S3 bucket.

Format Check (terraform fmt -check): Ensures code follows Terraform formatting standards.

Validation (terraform validate): Confirms Terraform configuration correctness.

Plan Execution (terraform plan -no-color -input=false -out planfile): Generates an execution plan for resource changes.

Error Handling (steps.plan.outcome == 'failure' → exit 1): Stops execution if planning fails.

*/